AWSTemplateFormatVersion: "2010-09-09"
Description: A sample CloudFormation template

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-unique-bucket-name
      AccessControl: Private
