name: Checkov Scan

on:
  pull_request:
    paths:
      - "**/*"

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan
        run: checkov -d ${{ github.workspace }} --skip-check CKV2_GHA_1 --framework all

      - name: Upload Checkov Results
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: checkov-results.json
