name: Checkov Scan

on:
  pull_request:
    paths:
      - "**/*" # Include all files in the pull request

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Use the version compatible with Checkov

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov Scan
        run: checkov -d ${{ github.workspace }} --output json > checkov_results.json

      - name: Upload Checkov Results
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: checkov_results.json
      - name: Display Checkov Results
        run: |
          cat checkov_results.json
