name: Checkov Scan

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/*.yaml"
      - "**/*.yml"
  push:
    paths:
      - "**/*.tf"
      - "**/*.yaml"
      - "**/*.yml"

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v1
        with:
          args: -d . --framework all

      - name: Comment on Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Checkov scan completed. Please review the findings.'
            })
