name: Checkov Scan

on:
  pull_request:
    paths:
      - "**/*" # Include all files in the pull request

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Use the version compatible with Checkov

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov Scan
        run: checkov -d ${{ github.workspace }} --skip-check CKV2_GHA_1 --output json > checkov_results.json

      - name: Upload Checkov Results
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: checkov_results.json

      - name: Find checkov-results.json
        run: |
          echo "Path to checkov-results.json:"
          ls -R $GITHUB_WORKSPACE | grep "checkov-results.json"

      - name: Post Comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const artifactPath = path.join(process.env.GITHUB_WORKSPACE, 'checkov-results');
            const resultsFilePath = path.join(artifactPath, 'checkov-results.json');
            const results = JSON.parse(fs.readFileSync(resultsFilePath, 'utf8'));
            const comment = `Checkov scan results:\n\nPassed checks: ${results.passed_checks.length}\nFailed checks: ${results.failed_checks.length}\nSkipped checks: ${results.skipped_checks.length}`;
            github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
            });
